### ISSUE TITLE
Compiliing from sources

### ISSUE THREAD

**Issue by Petrprogs** [mahomaps/mm-v1#102]
How to compile u'r project from sources? Is jdk for x64 or x32? Please, add manual for compiling from sources

**Comment by Feodor0090** [comment]
Like any other J2ME project.

WTK 2.5.2, jdk 1.6 x32. Check https://github.com/mahomaps/mm-v1/blob/main/build.sh for step-by-step for command line without IDE (in fact, there are just 3 calls for javac, preverify and jaring) and https://github.com/Feodor0090/j2me_compiler for exact used sdk versions.

**Comment by Petrprogs** [comment]
Ok, thanks. What IDE can i use for developing your project?

**Comment by Feodor0090** [comment]
On windows - any of your choice. Specific plugins for better integration exist for any eclipse version, old netbeans and old intelliJ. J2ME is just a 1.3 java with different `bootclasspath`, so in theory it's possible to configure any java ide to work with it. Personally i use eclipse. You will need 1.6 jdk, WTK and `MTJ` plugin.

On x86_64 linux, i know how to make it work only on latest debian/ubuntu and only using eclipse. Non-deb distors was never tested. x86_32 wasn't tested. Non-x86 archs won't work.

For further help with windows you better contact Shinovon via nnmidlets chat.
For further help with linux contact me in telegram.

**Comment by Petrprogs** [comment]
> On windows - any of your choice. Specific plugins for better integration exist for any eclipse version, old netbeans and old intelliJ. J2ME is just a 1.3 java with different `bootclasspath`, so in theory it's possible to configure any java ide to work with it. I'm using eclipse. You will need 1.6 jdk, WTK and `MTJ` plugin.
> 
> On x86_64 linux, i know how to make it work only on latest debian/ubuntu and only using eclipse. Non-deb distors was never tested. x86_32 wasn't tested. Non-x86 archs won't work.
> 
> For further help with windows you better contact Shinovon via nnmidlets chat. For further help with linux contact me in telegram.

Thanx for detailed info!
