### ISSUE TITLE
Add satelite map

### ISSUE THREAD

**Issue by Petrprogs** [mahomaps/mm-v1#111]

**Comment by Feodor0090** [comment]
This needs future `JS API` / web app reverse engineering to understand what options `core-renderer` wants to return non-scheme tiles.

**Comment by Petrprogs** [comment]
I already found satelite tiles url.
For example - for getting scheme tiles we use url like that: https://core-renderer-tiles.maps.yandex.net/tiles?l=map&lang=ru_RU&x=10104&y=5148&z=14
So for getting satelite tiles we will use url like that: https://core-sat.maps.yandex.net/tiles?l=sat&lang=ru_RU&x=10104&y=5148&z=14

Url for satelite tiles is: core-sat.maps.yandex.net
All params, instead of "l" key value are the same.

**Comment by shinovon** [comment]
@Petrprogs делаем?

**Comment by Feodor0090** [comment]
So tasklist is:
- Delete `allowDownload` flag and replace it with integer field (0=offline, 1=scheme, 2=sattelite), update settings screen
- Modify `getUrl` to use sattelite url.
- Add hotkey to switch scheme/sat (`0` key is still free)

You can implement all this and open PR if you want

**Comment by Feodor0090** [comment]
> @Petrprogs делаем?

Если это сделают за нас мне будет только проще

А ты если нечего делать сделай настройку прокси.

**Comment by Petrprogs** [comment]
> @Petrprogs делаем?

I think... Yes... But this will be not very fast :)

**Comment by shinovon** [comment]
> И определитесь на каком языке мы в этом репе общаемся, кстати

я это случайно из тг отправил, лол

**Comment by shinovon** [comment]
> И на тебе (@shinovon) ещё висит на сервере обратывать флаги телеметрии (чекни апдейт тред, там новый GET параметр шлётся)

давно сделано, читай чат хоть раз в год

**Comment by Petrprogs** [comment]
> > И определитесь на каком языке мы в этом репе общаемся, кстати
> 
> я это случайно из тг отправил, лол

Can you pls write in Eng?

**Comment by Feodor0090** [comment]
@shinovon мне в падлу
