### ISSUE TITLE
`GeoUpdateThread.<clinit>` is unsafe

### ISSUE THREAD

**Issue by Feodor0090** [mahomaps/mm-v1#128]
This works only because all tested JVMs follow https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-5.html#jvms-5.5 and call `<clinit>` only when the class is actually used. This happens when user requests geolocation from map screen. At this point, `LoadLocale()` is guaranteed to be called. Otherwise, you will get something like
```
java.lang.ExceptionInInitializerError
	at mahomaps.MahoMapsApp.<clinit>(MahoMapsApp.java:73)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at emulator.Emulator.main(A:955)
Caused by: java.lang.NullPointerException
	at mahomaps.map.GeoUpdateThread.<clinit>(GeoUpdateThread.java:153)
	... 4 more
```
While this will be the case only on VERY broken custom jvms, this is still bad due to being one of blockers to support dynamic language switch. That array should hold only numbers of texts, not texts themselves.

**Comment by shinovon** [comment]
Had that kind of problem in jt: class was initializing earlier than needed because of opened memoryview in kem
