### ISSUE TITLE
Application icon is too big and cropped on Symbian 9.1

### ISSUE THREAD

**Issue by artem78** [mahomaps/mm-v1#133]
![Snap4131](https://github.com/mahomaps/mm-v1/assets/8585304/295b354d-f5f7-4546-8357-ebb3b8d8924a)

**OS:**  Symbian 9.1
**Phone:** Nokia N95 8GB

**Comment by shinovon** [comment]
9.1 expects 48px icon and crops it. Main target is >= 9.2 and ^3 so wontfix.

**Comment by artem78** [comment]
> wontfix

Just a moment! I'm not familiar with Java, but in Symbian C++ it's possible to use Tiny-SVG format instead of raster. So icon will be well resized to any size.

See [documentation](https://disk.yandex.ru/i/J_iR_xwBBAdeRQ) (do you speak Russian?):

![20240207_201551](https://github.com/mahomaps/mm-v1/assets/8585304/17e66a7a-afa7-4ce5-ba36-bad24f9c97b8)

Also you make have a look at [one of my project](https://github.com/artem78/s60-gps-tracker). It uses only vector icon format. See [the commit](https://github.com/artem78/s60-gps-tracker/commit/96dd18c27b8f39ddf4f33dcd8db0968ed444d9ac).

By the way, in application list your icon looks correct and not cropped:

![Snap4130](https://github.com/mahomaps/mm-v1/assets/8585304/289b4aa3-60d9-44f8-9e23-e99814243570) ![Snap4134](https://github.com/mahomaps/mm-v1/assets/8585304/bfdf8b25-7292-4bc9-8ce4-d140fd673958)

**Comment by shinovon** [comment]
Конкретно в этом месте оно обрезается до 48px, а svg иконка уже используется
> ![image](https://github.com/mahomaps/mm-v1/assets/43963888/c35fb692-06fd-412a-b196-6ad326de72d7)

**Comment by artem78** [comment]
Хм... Ну тогда не знаю. Видимо особенность Джавы.
